export enum EventTypes {
  WSP_PICKING_SUBSTITUTION_PREFERENCES_V1 = 'WSP_PICKING_SUBSTITUTION_PREFERENCES_V1',
  WSP_PICKING_SUBSTITUTION_PROSPECT_APPROVAL = 'WSP_PICKING_SUBSTITUTION_PROSPECT_APPROVAL',
  WSP_PICKING_SUBSTITUTION_FINISHED = 'WSP_PICKING_SUBSTITUTION_FINISHED',
  LIDER_CALL_SOD_PICKING_SUBSTITUTION = 'LIDER_CALL_SOD_PICKING_SUBSTITUTION',
}
